// <auto-generated />
using Ecommerce.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231105181225_DatabaseCreation")]
    partial class DatabaseCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.1.23419.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Design Patterns"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Database Design"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Programming Languages"
                        });
                });

            modelBuilder.Entity("Ecommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            CategoryId = 1,
                            Description = "<p><strong>\"Don't Make Me Think\"</strong> by Steve Krug is a timeless guide to web usability, emphasizing a <strong>common-sense approach</strong>. Krug's insights on usability <strong>testing</strong>, <strong>navigation</strong>, and <strong>accessibility </strong>make it essential for web designers and developers seeking to create <em>user-friendly </em>websites.</p>",
                            ISBN = "0132350882",
                            ImageUrl = "\\images\\product\\d10bc571-0a5e-407d-8546-d9557acd8434.png",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "Don't Make Me Think"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Robert Nystrom",
                            CategoryId = 3,
                            Description = "<p><strong>\"The Art of Invisibility\"</strong> is a <strong>must-read</strong> guide to <strong>online privacy</strong> and <strong>digital security</strong>. In this book, the author provides <strong>vital strategies</strong> and <strong>real-world tactics</strong> to help readers protect their <strong>online identity</strong> and maintain <strong>personal privacy</strong> in today's digital age.</p>",
                            ISBN = "0990582906",
                            ImageUrl = "\\images\\product\\a0b3312a-a83d-467b-a576-9fb46c51c73d.png",
                            ListPrice = 40.0,
                            Price = 30.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "The Art of Invisibility"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Markus Winand",
                            CategoryId = 2,
                            Description = "<p><strong>\"Database Design for Mere Mortals\"</strong> is an essential <strong>guide</strong> for anyone interested in <strong>database design</strong>. It takes a <strong>practical</strong>, <strong>easy-to-follow</strong> approach to database concepts and design, making it perfect for <strong>beginners</strong> and <strong>professionals</strong> alike.</p>",
                            ISBN = " 3950307820",
                            ImageUrl = "\\images\\product\\cb840f66-4022-4c7d-b29d-cd568f481140.png",
                            ListPrice = 30.0,
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "Database Design Mere Mortals"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Martin Kleppmann",
                            CategoryId = 2,
                            Description = "<p><strong>\"Fundamentals of DBMS\"</strong> provides a solid foundation in <strong>Database Management Systems (DBMS)</strong>. This book offers <strong>comprehensive insights</strong> into database concepts, making it a <strong>crucial resource</strong> for <strong>students</strong> and <strong>professionals</strong> looking to grasp the core principles of DBMS.</p>",
                            ISBN = "1449373321",
                            ImageUrl = "\\images\\product\\e5c35414-2b59-4310-b91c-d5ffe400e70c.png",
                            ListPrice = 25.0,
                            Price = 23.0,
                            Price100 = 20.0,
                            Price50 = 22.0,
                            Title = "Fundamentals of DBMS"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Steve McConnell",
                            CategoryId = 3,
                            Description = "<p><strong>\"A Quick Guide to C# Programming\"</strong> is a <strong>fast-track</strong> resource for learning C# programming. With its <strong>concise explanations</strong> and <strong>hands-on examples</strong>, this book is ideal for <strong>beginners</strong> and <strong>intermediate</strong> programmers looking to master C# quickly.</p>",
                            ISBN = "0735619670",
                            ImageUrl = "\\images\\product\\a80ba6f9-3975-4ee1-aec4-def04cc33fc7.png",
                            ListPrice = 55.0,
                            Price = 50.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "A Quick Guide to C# Programming"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Andrew Hunt",
                            CategoryId = 1,
                            Description = "<p><strong>\"The Pragmatic Programmer\"</strong> is an <strong>indispensable resource</strong> for software developers. This book offers <strong>practical advice</strong> and <strong>timeless wisdom</strong> for becoming a more effective and efficient programmer. It is a <strong>must-read</strong> for both <strong>novice</strong> and <strong>experienced</strong> developers seeking to elevate their coding skills and practices.</p>",
                            ISBN = "020161622X",
                            ImageUrl = "\\images\\product\\5f2f504e-2cf1-4683-8b51-84b5e472e9ef.png",
                            ListPrice = 70.0,
                            Price = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Alex Xu",
                            CategoryId = 1,
                            Description = "<p>It provides a comprehensive guide for <strong>software engineers</strong> preparing for&nbsp;<em>technical interviews </em>focused on system design. It offers <strong>valuable insights</strong>, <strong>practical advice</strong>, and <strong>real-world examples</strong> to help readers tackle complex system design questions effectively.&nbsp;</p>",
                            ISBN = "978-1718501151",
                            ImageUrl = "\\images\\product\\efd94755-46bc-4f50-a716-d750228f5c20.png",
                            ListPrice = 90.0,
                            Price = 85.0,
                            Price100 = 70.0,
                            Price50 = 80.0,
                            Title = "System Design Interview"
                        },
                        new
                        {
                            Id = 8,
                            Author = "John Smith",
                            CategoryId = 3,
                            Description = "<p>It is an excellent resource for those looking to learn <strong>Python </strong>from <em>scratch</em>. It covers<strong> fundamental concepts </strong>and practical examples to help <strong>beginners </strong>build a strong foundation in <strong>Python programming</strong>.&nbsp;</p>",
                            ISBN = "978-1234567890",
                            ImageUrl = "\\images\\product\\bcce6385-9f66-470c-8724-cb58311908e8.png",
                            ListPrice = 92.0,
                            Price = 88.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "Python Programming"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Emily Johnson",
                            CategoryId = 2,
                            Description = "<p>&nbsp;It is an <em>indispensable </em>guide for anyone working with data &nbsp;for <strong>data professionals </strong>and <strong>analysts </strong>with the skills needed to <strong>clean, reshape, and transform data </strong>effectively using <strong>SQL. </strong>. It offers <em>practical guidance</em> on using <strong>SQL </strong>for <strong>data cleansing</strong>, <strong>transformation</strong>, and <strong>manipulation</strong>.&nbsp;</p>",
                            ISBN = "978-0987654321",
                            ImageUrl = "\\images\\product\\4260ed8a-af8f-4299-bd86-2a6a0518bca2.png",
                            ListPrice = 83.0,
                            Price = 76.0,
                            Price100 = 65.0,
                            Price50 = 70.0,
                            Title = "Data Wrangling with SQL"
                        });
                });

            modelBuilder.Entity("Ecommerce.Models.Product", b =>
                {
                    b.HasOne("Ecommerce.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
